application: APP_NAME
version: 1
runtime: go
api_version: go1

handlers:
- url: /api.js
  static_files: api/api.js
  upload: api/api.js

- url: /api/.*
  script: _go_app

- url: /
  static_files: web/index.html
  upload: web/index.html

- url: /(.+)
  static_files: web/\1
  upload: web/(.+)
